#!/usr/bin/env python3 -tt
import subprocess
import re
import time


def print_saw(saw, tagline, spacing):
    subprocess.Popen(["clear"]).communicate()
    print(tagline)
    if spacing != "-" and spacing != "partial":
        print(saw.replace("@", spacing))
        time.sleep(0.1)
    elif spacing == "partial":
        subprocess.Popen(["clear"]).communicate()
        print(tagline)
        print(re.sub(r"(@[\S\s])", r"", saw))
        time.sleep(0.1)
        subprocess.Popen(["clear"]).communicate()
        print(tagline)
        print(re.sub(r"(@[\S\s]{2})", r"", saw))
        time.sleep(0.1)
        subprocess.Popen(["clear"]).communicate()
        print(tagline)
        print(re.sub(r"(@[\S\s]{4})", r"", saw))
        time.sleep(0.1)
        subprocess.Popen(["clear"]).communicate()
        print(tagline)
        print(re.sub(r"(@[\S\s]{6})", r"", saw))
        time.sleep(0.1)
        subprocess.Popen(["clear"]).communicate()
        print(tagline)
        print(re.sub(r"(@[\S\s]{8})", r"", saw))
        time.sleep(0.1)
        subprocess.Popen(["clear"]).communicate()
        print(tagline)
        print(re.sub(r"(@[\S\s]{10})", r"", saw))
        time.sleep(0.1)
        subprocess.Popen(["clear"]).communicate()
        print(tagline)
        print(re.sub(r"(@[\S\s]{12})", r"", saw))
        time.sleep(0.1)
        subprocess.Popen(["clear"]).communicate()
        print(tagline)
        print(re.sub(r"(@[\S\s]{14})", r"", saw))
        time.sleep(0.1)
        subprocess.Popen(["clear"]).communicate()
        print(tagline)
        print(re.sub(r"(@[\S\s]{16})", r"", saw))
        time.sleep(0.1)
        subprocess.Popen(["clear"]).communicate()
        print(tagline)
        print(re.sub(r"(@[\S\s]{18})", r"", saw))
        time.sleep(0.1)
        subprocess.Popen(["clear"]).communicate()
        print(tagline)
        print(re.sub(r"(@[\S\s]{20})", r"", saw))
        time.sleep(0.1)
        subprocess.Popen(["clear"]).communicate()
        print(tagline)
        print(re.sub(r"(@[\S\s]{22})", r"", saw))
        time.sleep(0.1)
        subprocess.Popen(["clear"]).communicate()
        print(tagline)
        print(re.sub(r"(@[\S\s]{24})", r"", saw))
        time.sleep(0.1)
        subprocess.Popen(["clear"]).communicate()
        print(tagline)
        print(re.sub(r"(@[\S\s]{26})", r"", saw))
        time.sleep(0.1)
        subprocess.Popen(["clear"]).communicate()
        print(tagline)
        print(re.sub(r"(@[\S\s]{28})", r"", saw))
        time.sleep(0.1)
        subprocess.Popen(["clear"]).communicate()
        print(tagline)
        print(re.sub(r"(@[\S\s]{30})", r"", saw))
        time.sleep(0.1)
        subprocess.Popen(["clear"]).communicate()
        print(tagline)
        print(re.sub(r"(@[\S\s]{32})", r"", saw))
        time.sleep(0.1)
        subprocess.Popen(["clear"]).communicate()
        print(tagline)
        print(re.sub(r"(@[\S\s]{34})", r"", saw))
        time.sleep(0.1)
        subprocess.Popen(["clear"]).communicate()
        print(tagline)
        print(re.sub(r"(@[\S\s]{36})", r"", saw))
        time.sleep(0.1)
        subprocess.Popen(["clear"]).communicate()
        print(tagline)
        print(re.sub(r"(@[\S\s]{38})", r"", saw))
        time.sleep(0.1)
        subprocess.Popen(["clear"]).communicate()
        print(tagline)
        print(re.sub(r"(@[\S\s]{40})", r"", saw))
        time.sleep(0.1)
        subprocess.Popen(["clear"]).communicate()
        print(tagline)
        print(re.sub(r"(@[\S\s]{42})", r"", saw))
        time.sleep(0.2)
    else:
        pass
